# Compare Fiji and R measurements for CTCF analysis
#
# This script compares paired CTCF measurements generated by:
#   1. Fiji/ImageJ
#   2. An automated R workflow
#
# Expected input columns:
#   time_point
#   roi_id
#   fiji_ctcf
#   r_ctcf
#
# Example:
#   1h,Cell_01,18136.118,32182.400
#   1h,Cell_02,5578.463,78063.600
#   2h,Cell_01,9672.067,8482.510
#   4h,Cell_01,38887.327,37632.840


required_packages <- c(
  "dplyr",
  "tidyr",
  "readr",
  "ggplot2",
  "purrr",
  "tibble"
)


check_packages <- function(packages) {
  missing_packages <- packages[
    !vapply(
      packages,
      requireNamespace,
      logical(1),
      quietly = TRUE
    )
  ]

  if (length(missing_packages) > 0) {
    stop(
      "Missing packages: ",
      paste(missing_packages, collapse = ", "),
      "\nInstall them with:\n",
      "install.packages(c(",
      paste(sprintf('"%s"', missing_packages), collapse = ", "),
      "))"
    )
  }
}


check_packages(required_packages)

library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(purrr)
library(tibble)


validate_input <- function(data) {
  required_columns <- c(
    "time_point",
    "roi_id",
    "fiji_ctcf",
    "r_ctcf"
  )

  missing_columns <- setdiff(
    required_columns,
    names(data)
  )

  if (length(missing_columns) > 0) {
    stop(
      "The input file is missing these columns: ",
      paste(missing_columns, collapse = ", ")
    )
  }

  if (!is.numeric(data$fiji_ctcf)) {
    stop("Column 'fiji_ctcf' must be numeric.")
  }

  if (!is.numeric(data$r_ctcf)) {
    stop("Column 'r_ctcf' must be numeric.")
  }

  if (anyDuplicated(data[c("time_point", "roi_id")]) > 0) {
    warning(
      "Duplicate time_point and roi_id combinations were detected."
    )
  }

  invisible(TRUE)
}


prepare_comparison_data <- function(data) {
  validate_input(data)

  data %>%
    mutate(
      time_point = factor(
        time_point,
        levels = c("1h", "2h", "4h")
      ),
      difference = r_ctcf - fiji_ctcf,
      absolute_difference = abs(difference),
      pair_mean = (r_ctcf + fiji_ctcf) / 2,
      percent_difference = if_else(
        fiji_ctcf == 0,
        NA_real_,
        100 * difference / fiji_ctcf
      )
    ) %>%
    filter(
      !is.na(time_point),
      !is.na(fiji_ctcf),
      !is.na(r_ctcf)
    )
}


summarise_methods <- function(data) {
  long_data <- data %>%
    select(
      time_point,
      roi_id,
      Fiji = fiji_ctcf,
      R = r_ctcf
    ) %>%
    pivot_longer(
      cols = c(Fiji, R),
      names_to = "method",
      values_to = "CTCF"
    )

  long_data %>%
    group_by(time_point, method) %>%
    summarise(
      n = n(),
      mean_ctcf = mean(CTCF, na.rm = TRUE),
      median_ctcf = median(CTCF, na.rm = TRUE),
      sd_ctcf = sd(CTCF, na.rm = TRUE),
      se_ctcf = sd_ctcf / sqrt(n),
      min_ctcf = min(CTCF, na.rm = TRUE),
      max_ctcf = max(CTCF, na.rm = TRUE),
      .groups = "drop"
    )
}


summarise_differences <- function(data) {
  data %>%
    group_by(time_point) %>%
    summarise(
      n = n(),
      mean_fiji = mean(fiji_ctcf, na.rm = TRUE),
      mean_r = mean(r_ctcf, na.rm = TRUE),
      mean_difference = mean(difference, na.rm = TRUE),
      median_difference = median(difference, na.rm = TRUE),
      mean_absolute_difference = mean(
        absolute_difference,
        na.rm = TRUE
      ),
      sd_difference = sd(difference, na.rm = TRUE),
      lower_agreement = mean_difference -
        1.96 * sd_difference,
      upper_agreement = mean_difference +
        1.96 * sd_difference,
      .groups = "drop"
    )
}


calculate_correlations <- function(data) {
  safe_correlation <- function(x, y, method) {
    if (
      length(x) < 3 ||
      sd(x, na.rm = TRUE) == 0 ||
      sd(y, na.rm = TRUE) == 0
    ) {
      return(
        tibble(
          estimate = NA_real_,
          p_value = NA_real_
        )
      )
    }

    result <- cor.test(
      x,
      y,
      method = method,
      exact = FALSE
    )

    tibble(
      estimate = unname(result$estimate),
      p_value = result$p.value
    )
  }

  data %>%
    group_split(time_point) %>%
    map_dfr(function(group_data) {
      pearson <- safe_correlation(
        group_data$fiji_ctcf,
        group_data$r_ctcf,
        "pearson"
      )

      spearman <- safe_correlation(
        group_data$fiji_ctcf,
        group_data$r_ctcf,
        "spearman"
      )

      tibble(
        time_point = unique(group_data$time_point),
        n = nrow(group_data),
        pearson_r = pearson$estimate,
        pearson_p = pearson$p_value,
        spearman_rho = spearman$estimate,
        spearman_p = spearman$p_value
      )
    })
}


run_paired_tests <- function(data) {
  data %>%
    group_split(time_point) %>%
    map_dfr(function(group_data) {
      if (nrow(group_data) < 2) {
        return(
          tibble(
            time_point = unique(group_data$time_point),
            n = nrow(group_data),
            mean_difference = NA_real_,
            paired_t_p = NA_real_,
            wilcoxon_p = NA_real_
          )
        )
      }

      t_result <- t.test(
        group_data$r_ctcf,
        group_data$fiji_ctcf,
        paired = TRUE
      )

      wilcox_result <- tryCatch(
        wilcox.test(
          group_data$r_ctcf,
          group_data$fiji_ctcf,
          paired = TRUE,
          exact = FALSE
        ),
        error = function(e) NULL
      )

      tibble(
        time_point = unique(group_data$time_point),
        n = nrow(group_data),
        mean_difference = mean(
          group_data$r_ctcf -
            group_data$fiji_ctcf,
          na.rm = TRUE
        ),
        paired_t_p = t_result$p.value,
        wilcoxon_p = if (is.null(wilcox_result)) {
          NA_real_
        } else {
          wilcox_result$p.value
        }
      )
    })
}


plot_method_summary <- function(data) {
  summary_data <- summarise_methods(data)

  ggplot(
    summary_data,
    aes(
      x = time_point,
      y = mean_ctcf,
      fill = method
    )
  ) +
    geom_col(
      position = position_dodge(width = 0.8),
      width = 0.7
    ) +
    geom_errorbar(
      aes(
        ymin = pmax(mean_ctcf - se_ctcf, 0),
        ymax = mean_ctcf + se_ctcf
      ),
      position = position_dodge(width = 0.8),
      width = 0.2
    ) +
    labs(
      title = "CTCF Measurements: Fiji versus R",
      subtitle = "Bars show mean ± standard error",
      x = "Treatment time",
      y = "Corrected Total Cell Fluorescence",
      fill = "Method"
    ) +
    theme_minimal(base_size = 12) +
    theme(
      plot.title = element_text(face = "bold"),
      panel.grid.minor = element_blank(),
      legend.position = "top"
    )
}


plot_paired_points <- function(data) {
  long_data <- data %>%
    select(
      time_point,
      roi_id,
      Fiji = fiji_ctcf,
      R = r_ctcf
    ) %>%
    pivot_longer(
      cols = c(Fiji, R),
      names_to = "method",
      values_to = "CTCF"
    )

  ggplot(
    long_data,
    aes(
      x = method,
      y = CTCF,
      group = roi_id
    )
  ) +
    geom_line(
      alpha = 0.3
    ) +
    geom_point(
      size = 2
    ) +
    facet_wrap(
      ~ time_point,
      scales = "free_y"
    ) +
    labs(
      title = "Paired CTCF Measurements",
      subtitle = "Each line represents the same ROI measured by Fiji and R",
      x = "Measurement method",
      y = "CTCF"
    ) +
    theme_minimal(base_size = 12) +
    theme(
      plot.title = element_text(face = "bold"),
      panel.grid.minor = element_blank()
    )
}


plot_correlation <- function(data) {
  ggplot(
    data,
    aes(
      x = fiji_ctcf,
      y = r_ctcf
    )
  ) +
    geom_point(
      size = 2.5,
      alpha = 0.75
    ) +
    geom_abline(
      slope = 1,
      intercept = 0,
      linetype = "dashed"
    ) +
    geom_smooth(
      method = "lm",
      se = TRUE
    ) +
    facet_wrap(
      ~ time_point,
      scales = "free"
    ) +
    labs(
      title = "Agreement between Fiji and R CTCF Measurements",
      subtitle = "The dashed line represents perfect agreement",
      x = "Fiji CTCF",
      y = "R CTCF"
    ) +
    theme_minimal(base_size = 12) +
    theme(
      plot.title = element_text(face = "bold"),
      panel.grid.minor = element_blank()
    )
}


plot_bland_altman <- function(data) {
  agreement_data <- summarise_differences(data)

  plot_data <- data %>%
    left_join(
      agreement_data %>%
        select(
          time_point,
          mean_difference,
          lower_agreement,
          upper_agreement
        ),
      by = "time_point"
    )

  ggplot(
    plot_data,
    aes(
      x = pair_mean,
      y = difference
    )
  ) +
    geom_point(
      size = 2.5,
      alpha = 0.75
    ) +
    geom_hline(
      aes(yintercept = mean_difference),
      linetype = "solid"
    ) +
    geom_hline(
      aes(yintercept = lower_agreement),
      linetype = "dashed"
    ) +
    geom_hline(
      aes(yintercept = upper_agreement),
      linetype = "dashed"
    ) +
    facet_wrap(
      ~ time_point,
      scales = "free"
    ) +
    labs(
      title = "Bland–Altman Analysis",
      subtitle = "Difference is calculated as R minus Fiji",
      x = "Mean of Fiji and R CTCF",
      y = "Difference in CTCF"
    ) +
    theme_minimal(base_size = 12) +
    theme(
      plot.title = element_text(face = "bold"),
      panel.grid.minor = element_blank()
    )
}


compare_methods <- function(
    input_csv,
    output_dir = "outputs/method_comparison"
) {
  if (!file.exists(input_csv)) {
    stop("Input file not found: ", input_csv)
  }

  dir.create(
    output_dir,
    recursive = TRUE,
    showWarnings = FALSE
  )

  raw_data <- readr::read_csv(
    input_csv,
    show_col_types = FALSE
  )

  comparison_data <- prepare_comparison_data(raw_data)

  method_summary <- summarise_methods(comparison_data)
  difference_summary <- summarise_differences(comparison_data)
  correlation_summary <- calculate_correlations(comparison_data)
  paired_test_summary <- run_paired_tests(comparison_data)

  readr::write_csv(
    comparison_data,
    file.path(
      output_dir,
      "paired_ctcf_measurements.csv"
    )
  )

  readr::write_csv(
    method_summary,
    file.path(
      output_dir,
      "method_summary.csv"
    )
  )

  readr::write_csv(
    difference_summary,
    file.path(
      output_dir,
      "difference_summary.csv"
    )
  )

  readr::write_csv(
    correlation_summary,
    file.path(
      output_dir,
      "correlation_summary.csv"
    )
  )

  readr::write_csv(
    paired_test_summary,
    file.path(
      output_dir,
      "paired_tests.csv"
    )
  )

  summary_plot <- plot_method_summary(comparison_data)
  paired_plot <- plot_paired_points(comparison_data)
  correlation_plot <- plot_correlation(comparison_data)
  bland_altman_plot <- plot_bland_altman(comparison_data)

  ggsave(
    filename = file.path(
      output_dir,
      "fiji_r_summary.png"
    ),
    plot = summary_plot,
    width = 8,
    height = 6,
    dpi = 300
  )

  ggsave(
    filename = file.path(
      output_dir,
      "paired_measurements.png"
    ),
    plot = paired_plot,
    width = 10,
    height = 6,
    dpi = 300
  )

  ggsave(
    filename = file.path(
      output_dir,
      "fiji_r_correlation.png"
    ),
    plot = correlation_plot,
    width = 10,
    height = 6,
    dpi = 300
  )

  ggsave(
    filename = file.path(
      output_dir,
      "bland_altman.png"
    ),
    plot = bland_altman_plot,
    width = 10,
    height = 6,
    dpi = 300
  )

  message(
    "Comparison completed.\n",
    "Results saved to: ",
    normalizePath(output_dir)
  )

  list(
    data = comparison_data,
    method_summary = method_summary,
    difference_summary = difference_summary,
    correlations = correlation_summary,
    paired_tests = paired_test_summary,
    plots = list(
      summary = summary_plot,
      paired = paired_plot,
      correlation = correlation_plot,
      bland_altman = bland_altman_plot
    )
  )
}


# Example:
#
# results <- compare_methods(
#   input_csv = "data/fiji_r_ctcf_comparison.csv",
#   output_dir = "outputs/method_comparison"
# )
#
# print(results$method_summary)
# print(results$correlations)
# print(results$paired_tests)
